export const ROUTES = {
  HOME: '/',
  AUTH: '/activate/:token',
  ADMIN: '/account',
  REGISTER: '/register',
  CHANGE_PASSWORD: '/account/change-password',
  LOGIN: '/login',
  LOGOUT: '/logout',
  ACCOUNT: '/account/account-settings',
  ORDERS: '/account/orders',
  ACCOUNT_SETTING: '/account/account-settings',
  ADDRESS: '/account/address',
  PAYMENT: '/account/payment',
  HELP_CENTER: '/account/help-center',
  LEGAL_NOTICE: '/account/legal-notice',
  NOTIFICATION: '/account/notification',
  WISHLIST: '/account/wishlist',
};
