export const ROUTES = {
  HOME: '/',
  AUTH: '/activate/:token',
  ADMIN: '/account',
  REGISTER: '/register',
  CHANGE_PASSWORD: 'change-password',
  LOGIN: '/login',
  LOGOUT: '/logout',
  ACCOUNT: '/account/account-settings',
  ORDERS: 'orders',
  ACCOUNT_SETTING: 'account-settings',
  ADDRESS: 'address',
  PAYMENT: 'payment',
  HELP_CENTER: 'help-center',
  LEGAL_NOTICE: 'legal-notice',
  NOTIFICATION: 'notification',
  WISHLIST: 'wishlist',
};
